name: pdf_email_app
channels:
  - conda-forge
dependencies:
  - python=3.9
  - poppler
  - pip
  - pip:
      - streamlit>=1.28.0
      - pdf2image>=3.1.0
      - Pillow>=10.0.0
      - python-dotenv>=1.0.0
